name: Release Obsidian Plugin

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Build plugin
        run: npm run build

      - name: Prepare plugin bundle
        run: |
          mkdir -p temp_build
          cp main.js manifest.json styles.css temp_build/
          
          mv temp_build giga-notes
          
          TAG_VERSION="${GITHUB_REF#refs/tags/v}"
          echo "Updating manifest version to $TAG_VERSION"
          jq --arg version "$TAG_VERSION" '.version = $version' giga-notes/manifest.json > temp.json
          mv temp.json giga-notes/manifest.json
          
          zip -r giga-notes.zip giga-notes
          
          echo "Contents of ZIP archive:"
          unzip -l giga-notes.zip

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          
          gh release create "$TAG_NAME" \
            --title "$TAG_NAME" \
            giga-notes.zip