name: Release Obsidian plugin

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Build plugin
        run: |
          npm install
          npm run build

      - name: Create plugin ZIP
        run: |
          mkdir -p giga-notes
          cp main.js manifest.json styles.css giga-notes/
          
          zip -r giga-notes.zip giga-notes

      - name: Create release with ZIP
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          
          # Создаем релиз с ZIP-архивом
          gh release create "$tag" \
            --title="$tag" \
            giga-notes.zip